// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mgmnadmmslpyjtcygyna.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1nbW5hZG1tc2xweWp0Y3lneW5hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4MDcxNzQsImV4cCI6MjA1OTM4MzE3NH0.2KvlXca1vjscVSk2qUuuAoFbogtIl4Yv8VXimWGS48s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);